name: Generate static site

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 7 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      - name: Checkout winsiderss/systeminformer
        uses: actions/checkout@v4
        with:
          repository: winsiderss/systeminformer
          path: systeminformer
          fetch-depth: 0
          sparse-checkout: |
            phnt/include
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown2==2.4.10 Pygments
      - name: Generate docs
        run: |
          commit=$(git -C systeminformer rev-list HEAD -- phnt/include | head -n 1)
          cd main
          python -u generate_docs.py --path ../systeminformer/phnt/include --commit $commit
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./main/docs
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
