name: Spell check with Typos

on:
  workflow_dispatch:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check spelling of descriptions
        uses: crate-ci/typos@master
        with: 
          files: ./descriptions/
